### ISSUE TITLE
Add Shadow to Markers

### ISSUE THREAD

**Issue by JRHutson** [JRHutson/Food-Resource-Map#18]
http://leafletjs.com/examples/custom-icons.html

**Comment by JRHutson** [comment]
Added the shadow to the code but it's not displaying on the map.

**Comment by JRHutson** [comment]
@cityhubla The gh-pages branch has the code for the marker shadows but it's not displaying in the map. If you can take a look, I'd appreciate it.

**Comment by jgravois** [comment]
in constructor options, ~~`URL`~~ `Url` 
https://dl.dropboxusercontent.com/u/59331579/js/cluster-shadow.html

**Comment by JRHutson** [comment]
Ahhhhh... Thank you @jgravois. It's showing up now. Just need to tweak the positioning and transparency.
