### ISSUE TITLE
Optimize for Mobile.

### ISSUE THREAD

**Issue by JRHutson** [JRHutson/Food-Resource-Map#19]
http://leafletjs.com/examples/mobile.html

**Comment by JRHutson** [comment]
Added meta tag from the linked site. Seems to have solved scaling issues on mobile.

**Comment by jgravois** [comment]
nice one :+1:

**Comment by JRHutson** [comment]
@jgravois Thanks. I was amazed when it was such a simple solution. We're going to be embedding the map into an iFrame in Wordpress on the new Food Bank site. Do you know if this will cause an issue? Will it detect the size of the frame and scale appropriately or try to scale the map for the whole page?

**Comment by jgravois** [comment]
its definitely possible to create an iframe that fills [an entire page](http://stackoverflow.com/questions/3982422/full-screen-iframe), but nothing special is going to happen automatically on phones unless you define specific CSS for that situation.

i've done a few embedded maps for our [DIY bike shop](http://www.bikebbq.com/) in Redlands.  I'm lazy, but if i were going to add a full screen option, i probably would have just created an href link below the map for people to click if they wanted to get a closer look.

**Comment by JRHutson** [comment]
That was my thought for mobile users. We can just have a link for the Mobile Friendly version. I was concerned if the iFrame ends up being smaller whether the map would scale to the page and then have controls cut off by the frame.

**Comment by jgravois** [comment]
if you hardcode height/width pixel values, they likely would overflow.
can you use a percentage (like i do [here](http://www.bikebbq.com/2015/08/2nd-annual-redlands-strada-rossa.html))?

``` html
<iframe 
  frameborder="0" 
  height="400" 
  marginheight="0" 
  marginwidth="0" 
  scrolling="no" 
  src="http://johngravois.com/maps/stradarossaII.html" 
  width="100%">
</iframe>
```

**Comment by JRHutson** [comment]
That should work. I'll let you know if we have any issue.
