### ISSUE TITLE
Attribution.

### ISSUE THREAD

**Issue by JRHutson** [JRHutson/Food-Resource-Map#22]
Need to add attribution for icon to comply with CC license.

**Comment by jgravois** [comment]
what is the attribution text you need to add?

``` js
map.attributionControl.addAttribution('your text here')
```

**Comment by JRHutson** [comment]
Thanks @jgravois. The icon that the marker is based on is under a Creativd Commons license so we need to credit the designer. 

I figured it wouldn't be too hard so I've been focused on adding functionality.

**Comment by JRHutson** [comment]
Attribution added.

**Comment by jgravois** [comment]
:+1:
