### ISSUE TITLE
Use Map Bounds for Search

### ISSUE THREAD

**Issue by JRHutson** [JRHutson/Food-Resource-Map#39]
Added Use Map Bounds to geocoder, but the search box is still showing results from world.

![image](https://cloud.githubusercontent.com/assets/10876900/10528925/73a372d2-734e-11e5-8ada-dc57aa9b2548.png)

![image](https://cloud.githubusercontent.com/assets/10876900/10528929/7dccc754-734e-11e5-853b-030f3f0baedf.png)

**Comment by jgravois** [comment]
don't pass the string `'True'`,  pass the actual boolean [`true`](https://github.com/esri/esri-leaflet-geocoder#options) :smile:
same goes for the `expanded` option.

**Comment by JRHutson** [comment]
That worked! For some reason the expanded option was working previously. Both are working now though.
